image: sturdynetoci/docker-openwrt-imagebuilder:22.03.1-ipq40xx

build:
  stage: build
  script:
    - mkdir -p ./bin
    - ./build.sh
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - bin

pages:
  stage: deploy
  script:
    - mkdir -p "./public/${CI_COMMIT_REF_SLUG}"
    - mv LICENSE "./public/${CI_COMMIT_REF_SLUG}"
    - mv ${CI_PROJECT_DIR}/bin "./public/${CI_COMMIT_REF_SLUG}/images"
    - ./generate-webpage.sh "${CI_PROJECT_DIR}/public/${CI_COMMIT_REF_SLUG}" > "./public/${CI_COMMIT_REF_SLUG}/index.html"
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - bin