#!/bin/sh

ipset_var=$(ipset list | grep NFA4)
mwan3_set=$(mwan3 status | grep NFA4)
if [ ! -z "$ipset_var" ] && [ -z "$mwan3_set" ];
then
   logger "Restarting mwan3. ipset values not present."
   /etc/init.d/mwan3 restart
else
   logger "mwan3 values present"
fi
