#!/bin/sh /etc/rc.common
#
# start watchdog
#
# https://openwrt.org/docs/guide-developer/procd-init-script-example

# Init sequence
START=99
STOP=10
 

# PROCD
USE_PROCD=1

start_service()
{
    procd_open_instance lte_watchdog
    procd_set_param command /bin/sh "/usr/lib/lte_watchdog/lte_watchdog"
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1 # forward stdout of the command to logd
    procd_set_param stderr 1 # same for stderr
    procd_set_param pidfile /var/run/lte_watchdog.pid
    procd_close_instance
}

stop_service()
{
    logger -t "lte_watchdog" "watchdog stopped!"
}

 

service_triggers()
{
    procd_add_reload_trigger "lte_watchdog"
}

reload_service()
{
    stop
    start
}
