name: FOSSOLOGY SCAN

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["ipq40xx"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up FOSSology
      run: |
        # Run FOSSology scan
        curl -k -X POST -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2OTQzMDM5OTksIm5iZiI6MTY5MTYyNTYwMCwianRpIjoiTWk0eiIsInNjb3BlIjoid3JpdGUifQ.fp2upL5iVozQWIFa7aJ1F7imyDUkTCxbMBLrwt3ICMA" "http://35.90.154.168/repo/api/v1/scan" -F "file=@."
