name: FOSSOLOGY SCAN

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["ipq40xx"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Set up FOSSology
      #   env:
      #     FOSSOLOGY_API_TOKEN: ${{ secrets.FOSSOLOGY_API_TOKEN }}
      #   run: |
      #     # Replace with your FOSSology server URL
      #     FOSSOLOGY_SERVER_URL="http://35.90.154.168/repo"

      #     # Authenticate and get token
      #     FOSSOLOGY_TOKEN=$(curl -k -X POST -d "user=fossy" -d "password=password" "${FOSSOLOGY_SERVER_URL}/api/v1/tokens")

      #     # Extract token from response
      #     FOSSOLOGY_TOKEN=$(echo "$FOSSOLOGY_TOKEN" | jq -r '.token')

      #     # Run FOSSology scan
      #     curl -k -X POST -H "Authorization: ${FOSSOLOGY_TOKEN}" "${FOSSOLOGY_SERVER_URL}/api/v1/scan" -F "file=@."
