name: building sturdynet images (target->ipq40xx)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["ipq40xx"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    container: sturdynetoci/docker-openwrt-imagebuilder:22.03.1-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # BUILDING THE IMAGES
      - run: mkdir -p "${GITHUB_WORKSPACE}/bin"
      - run: ./build.sh
      - run: mkdir -p "${GITHUB_WORKSPACE}/public/${GITHUB_REF##*/}"
      - run: mv LICENSE "${GITHUB_WORKSPACE}/public/${GITHUB_REF##*/}"
      - run: mv "${GITHUB_WORKSPACE}/bin" "${GITHUB_WORKSPACE}/public/${GITHUB_REF##*/}/images"
      - run: ./generate-webpage.sh "${GITHUB_WORKSPACE}/public/${GITHUB_REF##*/}" > "${GITHUB_WORKSPACE}/public/${GITHUB_REF##*/}/index.html"
      
      # DEPLOYING THE IMAGE DOWNLOAD PAGE
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload public repository
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      
      # UPLOAD FIRWARE TO OPENWISP
      - name: LOGIN TO OPENWISP
        run: |
          echo OWISP_LOGIN_RESPONSE=::add-mask::$( \
          curl --request POST \
          --location 'https://owisp.sturdynet.net/api/v1/users/token/' \
          --header 'Content-Type:application/json' \
          --data '{"username":"${{ secrets.OWISP_USERNAME }}","password":"${{ secrets.OWISP_PASSWORD }}"}' \
          ) >> $GITHUB_ENV
      - name: GET OPENWISP BEARER TOKEN
        run: |
          echo OWISP_BEARER_TOKEN=::add-mask::$( \
          echo $OWISP_LOGIN_RESPONSE | sed "s/{.*\"token\":\"\([^\"]*\).*}/\1/g" \
          ) >> $GITHUB_ENV
      - run: echo "FIRMWARE_FILE_NAME=openwrt-22.03.1-ipq40xx-generic-glinet_gl-ap1300-squashfs-nand-sysupgrade.bin" >> $GITHUB_ENV
      - run: cd ${GITHUB_WORKSPACE}/public/${GITHUB_REF##*/}/images/ && chmod 777 ${FIRMWARE_FILE_NAME} && ls -l
      - run: echo "FIRMWARE_FILE_PATH=${GITHUB_WORKSPACE}/public/${GITHUB_REF##*/}/images/${FIRMWARE_FILE_NAME}" >> $GITHUB_ENV
      - name: UPLOAD FIRMWARE IMAGE TO OPENWISP
        run: |
          curl -v --location 'https://owisp.sturdynet.net/api/v1/firmware-upgrader/build/${{ secrets.OWISP_BUILD_ID }}/image/' \
          --header 'Authorization: Bearer ${{ env.OWISP_BEARER_TOKEN }}' \
          --form 'type="${{ env.FIRMWARE_FILE_NAME }}"' \
          --form 'file=@"${{ env.FIRMWARE_FILE_PATH }}"'
